# .streamlit/secrets.toml
# This file provides the credentials for Firebase (Firestore)

# Your Firebase Admin SDK JSON goes here. It must be a single line to avoid Streamlit errors.
firebase_config = """{
  "type": "service_account",
  "project_id": "utility-dynamo-436816-h1",
  "private_key_id": "bf319b8f567898a141f7c30b99f0c977cf4a9b2a",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClKAhrlartdNtf\ndE9Est8PecNiqy4x0TL3YVem0vcS4065l4wX/kV+vwfO+SrY9Vpzthf+FMKvvdBK\niN3JrT6XIh0mGVpg49laZcqoRUxU4aGp2mNnU2e+WpQWDK6Y+hAzf5TqbYmCkqDi\nwKMGUaN+nE+LiMS+oycUEDBNH34HfJRkRx3NdnGQHW0TCAn85M3BYthCzt644io7\noSbyGu2FHFDYVEp7VYa+O0R5hmjLHDB6Kunf+9+9e+zQySfzAauPPI32QlkBxqGj\n0eTNuOOVjB1pxTez8W/H69CJCWtlt8qBRNqbJV+FSK1PF7c1jkYxwfgEmLgL9pzO\nt1fdmN6NAgMBAAECggEADZTVMcOvuAc8DbAgNKNg+dd8Mcj8liwrPMdMe0jYozz+\nDv+0uDm4t/Y4S3+XU8VuwsU0A+OWfvflARFwQP12KtzV+M7CQpAkzOzsqsRyxSgo\n2zGSVb+OGyE9EZ3JXdsdKfRRPVX0pkAt6s0HRaXBBCW72jBNEurnyRvrskE8uUYW\nJsQDni+bf01X3FqZ9fAa1M4/bgB2yyHFcZpCkawPuItCeNiEs8W4xprolscM7G/6\nwFb6tNA8xTaQtrTFaef0gAvq55LBgAVRefVZOXtw0/QMWZyCIgy0YlwYJKYptdFx\nBYRQwMUzVr55fqXabk5209zHCtY0jysPFBhWQ46JAQKBgQDcqtFhuBKQpo0urjqC\nFCf9XvKzE+b5Om+sRRvKCVwVxMaAvHmc3pHmXzhZnhQ8aAdqi/i2JWJsOMGxRR5e\n4o0CwgbSZtj70WL2heoKFMrBIaQ5pnUm4wt5oi7pXxxBi4ZJQ1Wn+ERP2bnAaqK5\n9MJkCu0hdDQbVyyFDM7scph7FQKBgQC/mdDzVXVn3h+MFqg+ScuZDMIGtQ3sSjt9\nbDYfagOO815IgOvlJLFL7hmhLo8BR72pqvqTcBq0v3h2czZu8Cc2i5MzmqtvTC+p\noZJT39mBGqANrNn1RTyNLrVv7plCXSWnKm1RDH4QPifubCbIXF4yWZTbxpyhAtYV\nQ6VMlDHTmQKBgQDCA3oGlcXU4mrdMRiGB9zFG3b91jDMzgEjkLuHHkWVaiYxSAUQ\n1GupBe1QdflKxxhGKHzrAOGRTzGVf7TdLglW9Gr1ELIUbZu6LjGA3ZkKx15RxbXZ\nE+Sh8+OVEieQxXCy933XKiQ9pKt5rwgVwUoslaK6OCYcJ8Af1wwTvgmspQKBgHC6\nsDyq+DPPdaI3pm9XfcmjvvixR+rRViUaKNHczxEpUTy5VZFxQDtbcIrr2Mm5Cvcr\nmNhsadoUmWyfptQoyfmGr2n6Q4ltOtHENVLR7qfOIYNKQsbTIKg0Zh3gNR3drgyn\nor+/6N/nohjeWwchiW54VGPmfDsjbw/9x+DBhHtpAoGBALTxsz4FR2YAtMyboFko\nt9hUd44FYUf2SrquuZb+zg3CS41dJWT3VGF27d58mrM1RcgCgi8vUzPuPjl8eq51\n8nE7rLeHxOKLNnnTQV6LMDwi0tgdNWgeD807V8Yo/QScK0+KA+x865KS7nGBNPva\ndbkjamYNpuct/r3Xg8M4idNb\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-study-buddy-access@utility-dynamo-436816-h1.iam.gserviceaccount.com",
  "client_id": "115978700356130935887",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-study-buddy-access%40utility-dynamo-436816-h1.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}"""

# The App ID is used to create the artifact path in Firestore.
app_id = "ai-powered-study-buddy-live" 

# The authentication token is not strictly needed for this type of service account setup.
initial_auth_token = "dummy-token-placeholder"
